### ISSUE TITLE
Does this work with latitude and longitude?

### ISSUE THREAD

**Issue by zeuslawyer** [tiaanduplessis/sort-by-distance#3]
HI,
this is a really great starting point library, so thank you for making it!

i note the docs talk only in terms of points, and appears to be whole numbers.

can this work with lat/long?
I've tried and I'm getting this result for the first result in the array of results.

[ -37.812372822735, 144.959373049748, distance: NaN ]

thanks!

**Comment by thecookieorg** [comment]
Hi,

Are you passing the origin to the sortByDistance?
Here is the code that works for me:

```
const sortByDistance = require('sort-by-distance');
const points = [
      { longitude: -123.120735, latitude: 49.282730},
      { longitude: 18.424055, latitude: -33.924870},
    ]
    
    const opts = {
      yName: 'latitude',
      xName: 'longitude'
    }
    
    const origin = { longitude: this.state.usrLongitude, latitude: this.state.usrLatitude}

```

And my output looks like this:
`
{longitude: 18.424055, latitude: -33.92487, distance: 38.60495573316883}
{longitude: -123.120735, latitude: 49.28273, distance: 132.6178828936472}
`

Cheers,
Marko

**Comment by tiaanduplessis** [comment]
@zeuslawyer did @thecookieorg's answer resolve your issue?
